[package]
name = "r2e"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Quarkus-like ergonomic layer over Axum â€” declarative controllers, compile-time DI, and zero runtime reflection"

[features]
default = ["security", "events", "utils"]
full = ["security", "events", "utils", "data", "scheduler", "cache", "rate-limit", "openapi", "prometheus", "openfga", "ws", "multipart"]
security = ["dep:r2e-security"]
events = ["dep:r2e-events"]
utils = ["dep:r2e-utils"]
data = ["dep:r2e-data"]
scheduler = ["dep:r2e-scheduler"]
cache = ["dep:r2e-cache"]
rate-limit = ["dep:r2e-rate-limit"]
openapi = ["dep:r2e-openapi"]
prometheus = ["dep:r2e-prometheus"]
openfga = ["dep:r2e-openfga"]
validation = ["r2e-core/validation"]
ws = ["r2e-core/ws"]
multipart = ["r2e-core/multipart"]

[dependencies]
r2e-core = { path = "../r2e-core", version = "0.1.0" }
r2e-macros = { path = "../r2e-macros", version = "0.1.0" }
r2e-security = { path = "../r2e-security", version = "0.1.0", optional = true }
r2e-events = { path = "../r2e-events", version = "0.1.0", optional = true }
r2e-utils = { path = "../r2e-utils", version = "0.1.0", optional = true }
r2e-data = { path = "../r2e-data", version = "0.1.0", optional = true }
r2e-scheduler = { path = "../r2e-scheduler", version = "0.1.0", optional = true }
r2e-cache = { path = "../r2e-cache", version = "0.1.0", optional = true }
r2e-rate-limit = { path = "../r2e-rate-limit", version = "0.1.0", optional = true }
r2e-openapi = { path = "../r2e-openapi", version = "0.1.0", optional = true }
r2e-prometheus = { path = "../r2e-prometheus", version = "0.1.0", optional = true }
r2e-openfga = { path = "../r2e-openfga", version = "0.1.0", optional = true }
