[workspace]
members = [
    "quarlus-core",
    "quarlus-macros",
    "quarlus-cache",
    "quarlus-rate-limit",
    "quarlus-security",
    "quarlus-data",
    "quarlus-openapi",
    "quarlus-events",
    "quarlus-scheduler",
    "quarlus-cli",
    "quarlus-test",
    "quarlus-utils",
    "example-app",
]
resolver = "2"
