[package]
name = "example-postgres"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
r2e = { path = "../../r2e", features = ["postgres", "openapi", "utils"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono", "migrate"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
garde = { version = "0.22", features = ["derive"] }
schemars = "1"
chrono = { version = "0.4", features = ["serde"] }
