[package]
name = "quarlus-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "quarlus"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
toml_edit = "0.22"
minijinja = "2"
colored = "3"
