[package]
name = "quarlus-openapi"
version = "0.1.0"
edition = "2021"

[dependencies]
quarlus-core = { path = "../quarlus-core" }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
