[package]
name = "r2e-compile-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]

[dev-dependencies]
r2e = { path = "../r2e", features = ["full"] }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
trybuild = "1"
